#!/bin/sh
pwd=`pwd`
resid="resid-0.16"
dirs="libsidplay libsidutils builders/resid-builder builders/hardsid-builder"

test ! -r "resid" && ln -sf "$resid" "resid"
test ! -r "unix" && ln -sf libsidplay/unix unix

cat >builders/Makefile.am <<EOF
SUBDIRS = resid-builder

if HARDSID
SUBDIRS += hardsid-builder
endif
EOF

for d in $dirs; do
  cd $pwd/$d
  echo "Bootstrapping $d..."
  if ! ./bootstrap; then
    exit
  fi
done
cd $pwd

echo "Bootstrapping sidplay-libs..."
aclocal --force
automake --force --add-missing --copy
autoconf --force
