.\" Copyright 2000 Simon White (s_a_white@email.com)
.\" Copyright 2000 Mikko Kilponen (mikil@uni.kaapeli.net)
.TH SIDPLAY 1 "19 September 2000" "SID Player Application"
.SH NAME
SIDPLAY \- Sidplay is SID-chip emulator for playing Commodore 64 music.
.SH SYNOPSIS
.B sidplay\ 
.I [ OPTIONS... ]
.B <datafile>
.br
.B sidplay2
.I [ OPTIONS... ]
.B <datafile>
.SH DESCRIPTION
.B Sidplay is a music player that emulates various components from a Commodore 64 (C64) computer.  The result is a program which can load and execute C64 machine code programs which produce music and sound.  This page covers both Sidplay versions 1 and 2, Sidplay being an frame based emulation capable of playback on low  specification PCs.  Sidplay2 on the other hand has been designed for accuracy which results in a much higher cpu usuage.  Additional playback modes have however been provided to allow playback on low specification machines at the cost of accuracy, but it still has a higher cpu demand than Sidplay.
.SH COMMON OPTIONS
.TP
\fB\--help|-h\fR
Display help.
.TP
\fB\-f<num>\fR
Set frequency in Hz. (default: 44100)
.TP
\fB\-nf\fR
No filter emulation.  Will reduce CPU overhead at the cost of reduced sound quality.
.TP
\fB\-ns\fR
Emulate MOS8580 waveforms. (default: MOS6581)
.TP
\fB\-o<num>\fR
Select track number. (default: preset)
.TP
\fB\-s\fR
Stereo Hardware support.  However even when enabled the left and right channels will be playing the same music unless the song is identified as being stereo.  For Sidplay other options are provided to produce special effects when in stereo mode, but Sidplay2 does not as yet support these.
.TP
\fB\-v\fR
Verbose output while playing.


.SH SIDPLAY2 OPTIONS
.TP
\fB\-fd\fR
Force dual sid environment.
This forces emulation of  2 sid-chips for stereo playback
even if datafile is identified as only being mono.  This occurs
in the case of the stereo sid format as currently there is no way
to identfy them.  Stereo MUS files are however automatically
detected.  The second sid appears in the 0xD500 address range.
.TP
\fB\-ne\fR
No external filter emulation.  Will reduce CPU overhead at the cost of reduced sound quality.
.TP
\fB\-nf<name>\fR
New SID filter description filename using an ini file format.
.TP
\fB\-p<num>\fR
Set bit precision for samples. The default is 16, but this value will be affected by the hardware available on the platform you are running..
.TP
\fB\-sl\fR
Left channel only.
Playback left channel only from stereo datafile.
.TP
\fB\-sr\fR
Right channel only.
Playback right channel only from stereo datafile.
.TP
\fB\-O<num>\fR
Optimisation level. (default: 0)
.br
Optimisation\ 0\ -\ C64 emulation is kept fully cycle synced at all times and requires atleast a P300 for mono sid tunes.  Stereo sid tunes are expected to require a greater CPU.
.br
Optimisation\ 1\ -\ Allows the CPU to run by itself and only regains sync with the Sound Interface Device (SID) when a sample is required.  This reduces sound accuracy, but does allow playback of mono sids on a P166.  Again stereo sids require faster CPUs.
.TP
\fB\-t<num>\fR
Set play length in [mins]:secs format. (0 is endless)
.TP
\fB\-vn\fR
Set VIC NTSC clock speed (America, 60Hz).
.TP
\fB\-vp\fR
Set VIC PAL clock speed (Europe, 50Hz).
.TP
\fB\-w\fR
Create WAV-file.  Output filename is <datafile>.wav and currently cannot be changed

.SH SIDPLAY OPTIONS
.TP
\fB\-a\fR
strict PlaySID song compatibility (read the docs!).
.TP
\fB\-a2\fR
bank switching mode (overrides -a).
.TP
\fB\-16\fR
enable 16-bit sample mixing.
.TP
\fB\-ss\fR
enable stereo surround.
.TP
\fB\-pc\fR
enable centered auto-panning (stereo only).
.TP
\fB\-n\fR
set NTSC clock speed (default: PAL).
.TP
\fB\-c\fR
force song speed = clock speed (PAL/NTSC).
.TP
\fB\-bn<num>\fR
set number of audio buffer fragments to use.
.TP
\fB\-bs<num>\fR
set size 2^<num> of audio buffer fragments.
.TP
\fB\-b<num>\fR
set sample buffer size.

.RS
.SH NOTES
Place for notes..
.SH OTHER INFORMATION
Sidplay2 Homepage:
    http://sidplay2.sourceforge.net/
.br
Sidplay homepage:
    http://www.geocities.com/SiliconValley/Lakes/5147/
.br
High Voltage Sid Collection (HVSC):
    http://hvsc.c64.org/
.SH AUTHORS
sidplay2     - Simon White <sidplay2@email.com>
.br
sidplay      - Michael Schwendt <sidplay@geocities.com>
.br
reSID engine - Dag Lem <resid@nimrod.no>
.br
man-page     - Mikko Kilponen <mikil@uni.kaapeli.net>
